#!/usr/bin/env bash

TARGET=$1

ALLOWED_TARGETS=("jester" "blackrain")

if [[ ! " ${ALLOWED_TARGETS[@]} " =~ " ${TARGET} " ]]; then
  echo "Invalid target. Allowed targets: ${ALLOWED_TARGETS[@]}"
  exit 1
fi

nixos-rebuild --use-remote-sudo --build-host root@$TARGET --target-host root@$TARGET --flake .#$TARGET --fast switch
